workflows:
  ios_testflight:
    name: iOS Release (Capacitor) - TestFlight
    max_build_duration: 90
    environment:
      groups:
        - ios
      node: 22
      xcode: latest
      vars:
        IOS_DIR: "ios/App"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.fantaf1.app"
        VITE_API_URL: "https://laqjyqfnjnofmvgedunl.supabase.co/functions/v1/fanta-api"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fantaf1.app
    triggering:
      events:
        - push
    scripts:
      - name: Install deps
        script: npm ci
      - name: Build web
        script: |
          cd web
          npm ci
          VITE_API_URL=$VITE_API_URL npm run build
      - name: Sync Capacitor iOS
        script: npx cap sync ios
      - name: Install iOS pods (if Podfile exists)
        script: |
          if [ -f "$IOS_DIR/Podfile" ]; then
            cd "$IOS_DIR"
            pod install
          fi
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA (signed) + Upload to TestFlight
        script: |
          cd "$IOS_DIR"
          if [ -d "App.xcworkspace" ]; then
            BUILD_TARGET="-workspace App.xcworkspace"
          else
            BUILD_TARGET="-project App.xcodeproj"
          fi
          xcodebuild \
            $BUILD_TARGET \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/build/ios/archive/App.xcarchive" \
            archive
          printf '<?xml version="1.0" encoding="UTF-8"?>\n' > "$CM_BUILD_DIR/exportOptions.plist"
          printf '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '<plist version="1.0">\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '<dict>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <key>method</key>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <string>app-store</string>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <key>teamID</key>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <string>L4252U7H8L</string>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <key>signingStyle</key>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <string>manual</string>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <key>provisioningProfiles</key>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <dict>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '    <key>com.fantaf1.app</key>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '    <string>Fanta F1 ios_app_store 1769663733</string>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  </dict>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <key>stripSwiftSymbols</key>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <true/>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <key>compileBitcode</key>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '  <false/>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '</dict>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          printf '</plist>\n' >> "$CM_BUILD_DIR/exportOptions.plist"
          mkdir -p "$CM_BUILD_DIR/build/ios/ipa"
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/ios/archive/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
    publishing:
      scripts:
        - name: Upload to TestFlight
          script: |
            KEY_ID="7XRTBU8623"
            ISSUER_ID="4c4f8539-f816-4f20-89ec-83b73e49eee0"
            mkdir -p ~/private_keys
            
            if [ -n "$APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY" ]; then
              echo "Using APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY"
              echo "$APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY" | base64 --decode > ~/private_keys/AuthKey_${KEY_ID}.p8
            elif [ -n "$_CONNECT_PUBLISHER_PRIVATE_KEY" ]; then
              echo "Using _CONNECT_PUBLISHER_PRIVATE_KEY"
              echo "$_CONNECT_PUBLISHER_PRIVATE_KEY" | base64 --decode > ~/private_keys/AuthKey_${KEY_ID}.p8
            else
              echo "ERROR: No private key variable found!"
              exit 1
            fi

            ls -l ~/private_keys/AuthKey_${KEY_ID}.p8
            xcrun altool --upload-app \
              --type ios \
              --file "$CM_BUILD_DIR/build/ios/ipa/App.ipa" \
              --apiKey "$KEY_ID" \
              --apiIssuer "$ISSUER_ID"

  android_release:
    name: Android Release (APK/AAB)
    max_build_duration: 60
    environment:
      node: 22
      vars:
        ANDROID_DIR: "android"
        VITE_API_URL: "https://laqjyqfnjnofmvgedunl.supabase.co/functions/v1/fanta-api"
    triggering:
      events:
        - push
    scripts:
      - name: Install deps
        script: npm ci
      - name: Build web
        script: |
          cd web
          npm ci
          VITE_API_URL=$VITE_API_URL npm run build
      - name: Add/Sync Android
        script: |
          npx cap add android || true
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
